import assert from 'node:assert/strict';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
const endpoint=process.argv[2]||'http://localhost:8790/mcp';
const client=new Client({name:'release-verification',version:'1.0.0'});
await client.connect(new StreamableHTTPClientTransport(new URL(endpoint)));
const list=await client.listTools();assert.equal(list.tools.length,12);console.log('PASS initialize and 12 tools');
const cases=[['prepare_to_meet_mike',{interests:'AI and education'},x=>assert.equal(x.profile.name,'Michael Bailey')],['get_booking_link',{minutes:45},x=>assert.equal(x.links[0].url,'https://calendar.app.google/QXKNDWh28PUFf9HSA')],['calculate_power',{solve_for:'power',assumptions:{clustered:true,kGiven:60,m:30},include_code:true},x=>{assert.ok(Math.abs(x.result.power-.759730429986494)<1e-10);assert.ok(x.code.R.length>100);assert.ok(x.defaulted_fields.includes('icc'));}],['calculate_power',{solve_for:'mde',assumptions:{clustered:true,kGiven:60,m:30}},x=>assert.ok(Math.abs(x.result.mde-.2102604704828857)<1e-10)],['calculate_power',{solve_for:'n',assumptions:{clustered:true,m:30,costPer:20,costCluster:100,budget:100000}},x=>{assert.equal(x.result.clusters,68);assert.ok(x.budget);}],['power_sensitivity',{solve_for:'power',scenarios:[{label:'Low ICC',assumptions:{clustered:true,icc:.01}},{label:'High ICC',assumptions:{clustered:true,icc:.1}}]},x=>assert.ok(x.scenarios[0].result.power>x.scenarios[1].result.power)],['list_datasets',{},x=>assert.equal(x.migration.rows,1563154)],['query_social_connections',{origin:'Guatemala',limit:3},x=>assert.equal(x.results.length,3)],['query_cross_gender_ties',{geography:'country',places:['Norway','Saudi Arabia']},x=>{assert.equal(x.results.length,2);assert.ok(x.results[0].cgfr>x.results[1].cgfr);}],['query_cross_gender_ties',{geography:'us_county',rank:'lowest',limit:5,cutoff:50},x=>{assert.equal(x.results.length,5);assert.equal(x.results[0].rank_ascending,1);}],['query_cross_gender_ties',{geography:'us_county',places:['Middlesex County, MA']},x=>assert.equal(x.results[0].id,'25017')],['social_capital_lab',{},x=>assert.equal(x.measures.length,3)],['query_social_capital',{geography:'county',query:'Middlesex, Massachusetts'},x=>assert.ok(x.results.length===1)],['query_social_capital',{geography:'zip',query:'02139'},x=>assert.equal(x.results[0].zip,'02139')],['query_migration',{origin:'Colombia',destination:'US',start_month:'2022-01',end_month:'2022-12'},x=>{assert.equal(x.results.length,12);assert.ok(x.observed_total>0);}],['find_ai_evidence',{query:'teachers tutoring'},x=>assert.ok(x.results.length>0)],['develop_evaluation_idea',{program:'AI job coach'},x=>assert.ok(x.questions.length>5)]];
for(const [name,args,verify]of cases){const r=await client.callTool({name,arguments:args});assert.ok(!r.isError,JSON.stringify(r));const data=r.structuredContent||JSON.parse(r.content[0].text);verify(data);console.log('PASS',name,JSON.stringify(args).slice(0,100));}
for(const [name,args]of [['query_migration',{origin:'Colombia',destination:'US',start_month:'2023-01'}],['query_social_connections',{origin:'Atlantis'}],['calculate_power',{solve_for:'power',assumptions:{tut:0,tuc:0}}],['calculate_power',{solve_for:'mde',assumptions:{clustered:true,kGiven:40,nGiven:2000}}],['query_cross_gender_ties',{geography:'country'}],['query_cross_gender_ties',{geography:'us_county',places:['Nowhere County, ZZ']}]]){assert.equal((await client.callTool({name,arguments:args})).isError,true);console.log('PASS rejected invalid input',name);}
assert.equal((await client.listResources()).resources.length,4);assert.equal(JSON.parse((await client.readResource({uri:'https://michaelbailey.org/mcp/lab'})).contents[0].text).measures.length,3);assert.equal((await client.listPrompts()).prompts.length,1);
assert.ok((await client.readResource({uri:'https://michaelbailey.org/mcp/profile'})).contents.length);
assert.ok((await client.getPrompt({name:'prepare-a-conversation',arguments:{interests:'AI education'}})).messages.length);
await client.close();
assert.equal((await fetch(endpoint+'/health')).status,200);assert.equal((await fetch(endpoint+'/absent')).status,404);
assert.equal((await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:'a'.repeat(66000)})).status,413);
console.log('PASS resources, prompts, HTTP limits. Endpoint:',endpoint);
// Access policy: a person in a browser gets a plain refusal on every /mcp path; no HTML is ever served.
const browser={Accept:'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Sec-Fetch-Dest':'document','Sec-Fetch-Mode':'navigate'};
for(const p of['','/','/health','/catalog','/data/profile.json','/nowhere']){const r=await fetch(endpoint+p,{headers:browser,redirect:'manual'});assert.equal(r.status,403,p);assert.equal(await r.text(),'humans not allowed',p);assert.match(r.headers.get('content-type'),/text\/plain/);}
assert.equal((await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:'{"hello":"world"}'})).status,403);
// A fetch-only agent (browser-like Accept, but no Sec-Fetch navigation headers) is greeted and shown the way in.
const agentGet=await fetch(endpoint,{headers:{Accept:'text/html,*/*;q=0.8','User-Agent':'ChatGPT-User/1.0'}});
assert.equal(agentGet.status,200);assert.match(agentGet.headers.get('content-type'),/text\/plain/);
const greeting=await agentGet.text();assert.match(greeting,/^Hello, friend/);assert.ok(greeting.includes('/mcp/catalog'));
console.log('PASS humans not allowed on every /mcp path; fetch-only agents greeted; non-JSON-RPC POST refused');
